spring:
  application:
    name: BackendExercise
  cache:
    type: redis
  data:
    redis:
      port: 6379
      host: localhost

tor:
  exit:
    nodes:
      url: https://check.torproject.org/exit-addresses
      refresh:
        rate: 3600000
server:
  port: 1024
management:
  endpoints:
    web:
      exposure:
        include: health,info
